version: "3.8"

services:
    app:
        build:
            context: .
            target: production
        ports:
            - "8000:8000"
        environment:
            - DATABASE_URL=postgresql+psycopg_async://aivision:password@db:5432/maindb
            - APP_ENV=production
            - MODEL_DEVICE=cuda
        depends_on:
            db:
                condition: service_healthy
        networks:
            - aivision-net

    db:
        image: postgres:14-alpine
        environment:
            POSTGRES_USER: aivision
            POSTGRES_PASSWORD: password
            POSTGRES_DB: maindb
        volumes:
            - postgres_data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U aivision -d maindb"]
            interval: 5s
            timeout: 5s
            retries: 5
        networks:
            - aivision-net

networks:
    aivision-net:
        driver: bridge

volumes:
    postgres_data:
