version: "3.8"

services:
    app:
        build:
            target: development
        environment:
            - APP_ENV=development
            - LOG_LEVEL=DEBUG
        volumes:
            - .:/app
            - /app/venv
