FROM postgres:14-bullseye

# Install build dependencies
RUN apt-get update && \
    apt-get install -y \
    git \
    make \
    gcc \
    postgresql-server-dev-14 \
    llvm \
    clang

# Clone and build pgvector
RUN git clone --branch v0.5.1 https://github.com/pgvector/pgvector.git \
    && cd pgvector \
    && make OPTFLAGS="" \
    && make install